# Generated by Django 4.2.30 on 2026-09-30 18:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stockreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, help_text='Purchase Order number (auto-generated if blank on create)', max_length=100)),
                ('vendor_code', models.CharField(blank=True, default='', help_text='Vendor code from vendor_buyer_master', max_length=100)),
                ('vendor_name', models.CharField(db_index=True, help_text='Vendor name (denormalized for display)', max_length=255)),
                ('buyer_name', models.CharField(blank=True, default='', help_text='Buyer responsible for this PO', max_length=255)),
                ('expected_delivery_date', models.DateField(db_index=True, help_text='Expected arrival date of this delivery')),
                ('promised_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Promised delivery quantity', max_digits=12)),
                ('carrier_or_tracking', models.CharField(blank=True, default='', help_text='Carrier name or tracking reference', max_length=255)),
                ('delivery_status', models.CharField(choices=[('CONFIRMED_ON_TRACK', 'Confirmed On Track'), ('IN_TRANSIT', 'In Transit'), ('PARTIAL_PROMISE', 'Partial Promise'), ('DELAYED_AT_RISK', 'Delayed At Risk'), ('CANCELLED', 'Cancelled'), ('CRITICAL_NO_PO', 'Critical - No PO')], db_index=True, default='CONFIRMED_ON_TRACK', help_text='Current delivery status', max_length=30)),
                ('notes', models.TextField(blank=True, default='', help_text='Free-text notes about this delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(db_column='component_code', help_text='Component this delivery is for', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='core.rmpmcomponentmaster', to_field='component_code')),
                ('week', models.ForeignKey(blank=True, db_column='week_code', help_text='Week bucket resolved from expected_delivery_date (server-side)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_schedules', to='core.weekdefinition', to_field='week_code')),
            ],
            options={
                'verbose_name': 'Vendor Delivery Schedule',
                'verbose_name_plural': 'Vendor Delivery Schedules',
                'db_table': 'vendor_delivery_schedule',
                'ordering': ['expected_delivery_date', 'component'],
            },
        ),
        migrations.CreateModel(
            name='MondayReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, help_text='Month in YYYY-MM format', max_length=7)),
                ('component_code', models.CharField(blank=True, db_index=True, help_text='Optional: specific component code the action is about', max_length=100, null=True)),
                ('component_description', models.CharField(blank=True, default='', help_text='Description of the component (denormalized)', max_length=255)),
                ('issue_type', models.CharField(choices=[('RM_SHORTAGE', 'RM Shortage'), ('BACKLOG_RECOVERY', 'Backlog Recovery'), ('VENDOR_DELAY', 'Vendor Delay'), ('CAPACITY_LINE_SPEED', 'Capacity / Line Speed'), ('QUALITY_HOLD', 'Quality Hold')], db_index=True, help_text='Category of the issue', max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('impact_summary', models.TextField(blank=True, default='', help_text='Summary of the business impact')),
                ('status', models.CharField(choices=[('PENDING_DISCUSSION', 'Pending Discussion'), ('AMICABLE_SOLUTION_AGREED', 'Amicable Solution Agreed'), ('ESCALATED_LEVEL_1', 'Escalated Level 1'), ('ESCALATED_LEVEL_2', 'Escalated Level 2'), ('ESCALATED_LEVEL_3', 'Escalated Level 3'), ('RESOLVED', 'Resolved')], db_index=True, default='PENDING_DISCUSSION', help_text='Current action status', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Notes about how this was / will be resolved')),
                ('agreed_action', models.TextField(blank=True, default='', help_text='The specific action agreed upon during the meeting')),
                ('assigned_owner', models.CharField(blank=True, default='', help_text='Person assigned to resolve this action', max_length=255)),
                ('target_resolution_date', models.DateField(blank=True, help_text='Target date to resolve this action', null=True)),
                ('escalated_to', models.CharField(blank=True, default='', help_text='Person/role this was escalated to (if escalated)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fg', models.ForeignKey(db_column='fg_code', help_text='Finished Good this action relates to', on_delete=django.db.models.deletion.CASCADE, related_name='monday_review_actions', to='core.bomfgheader', to_field='fg_code')),
                ('week', models.ForeignKey(db_column='week_code', help_text='Week this action was logged for', on_delete=django.db.models.deletion.CASCADE, related_name='monday_review_actions', to='core.weekdefinition', to_field='week_code')),
            ],
            options={
                'verbose_name': 'Monday Review Action',
                'verbose_name_plural': 'Monday Review Actions',
                'db_table': 'monday_review_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FGPlanFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, help_text='Month in YYYY-MM format', max_length=7)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('FROZEN', 'Frozen')], db_index=True, default='DRAFT', help_text='Current freeze status', max_length=10)),
                ('frozen_at', models.DateTimeField(blank=True, help_text='Timestamp when status transitioned to FROZEN (set server-side)', null=True)),
                ('frozen_by', models.CharField(blank=True, default='', help_text='Name/role of the person who froze the plan', max_length=255)),
                ('freeze_notes', models.TextField(blank=True, default='', help_text='Notes about why the plan was frozen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fg', models.ForeignKey(db_column='fg_code', help_text='Finished Good this freeze applies to', on_delete=django.db.models.deletion.CASCADE, related_name='plan_freezes', to='core.bomfgheader', to_field='fg_code')),
                ('week', models.ForeignKey(db_column='week_code', help_text='Week this freeze applies to', on_delete=django.db.models.deletion.CASCADE, related_name='plan_freezes', to='core.weekdefinition', to_field='week_code')),
            ],
            options={
                'verbose_name': 'FG Plan Freeze',
                'verbose_name_plural': 'FG Plan Freezes',
                'db_table': 'fg_plan_freeze',
                'ordering': ['month', 'fg'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryScheduleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, help_text='Denormalized PO number for audit persistence', max_length=100)),
                ('component_code', models.CharField(db_index=True, help_text='Denormalized component code for audit persistence', max_length=100)),
                ('vendor_name', models.CharField(blank=True, default='', help_text='Denormalized vendor name', max_length=255)),
                ('changed_by', models.CharField(help_text='Name of the person who made the change', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of the change')),
                ('field_changed', models.CharField(help_text='Description of which field(s) were changed', max_length=500)),
                ('old_value', models.TextField(blank=True, default='', help_text='Previous value before the change')),
                ('new_value', models.TextField(blank=True, default='', help_text='New value after the change')),
                ('reason_for_change', models.TextField(help_text='Mandatory reason for the change (minimum 10 characters)')),
                ('schedule', models.ForeignKey(blank=True, help_text='FK to the schedule row (SET_NULL if schedule is deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='core.vendordeliveryschedule')),
            ],
            options={
                'verbose_name': 'Delivery Schedule Change Log',
                'verbose_name_plural': 'Delivery Schedule Change Logs',
                'db_table': 'delivery_schedule_change_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendordeliveryschedule',
            index=models.Index(fields=['component', 'week'], name='vendor_deli_compone_1d5083_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordeliveryschedule',
            index=models.Index(fields=['delivery_status'], name='vendor_deli_deliver_1fc11d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordeliveryschedule',
            index=models.Index(fields=['expected_delivery_date'], name='vendor_deli_expecte_9c7349_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordeliveryschedule',
            index=models.Index(fields=['po_number'], name='vendor_deli_po_numb_efe994_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordeliveryschedule',
            index=models.Index(fields=['vendor_name'], name='vendor_deli_vendor__e992b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendordeliveryschedule',
            constraint=models.UniqueConstraint(fields=('po_number', 'component', 'expected_delivery_date'), name='unique_delivery_schedule_entry'),
        ),
        migrations.AddIndex(
            model_name='mondayreviewaction',
            index=models.Index(fields=['month', 'week', 'fg'], name='monday_revi_month_a23846_idx'),
        ),
        migrations.AddIndex(
            model_name='mondayreviewaction',
            index=models.Index(fields=['status'], name='monday_revi_status_6a475e_idx'),
        ),
        migrations.AddIndex(
            model_name='mondayreviewaction',
            index=models.Index(fields=['issue_type'], name='monday_revi_issue_t_da6ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='mondayreviewaction',
            index=models.Index(fields=['month', 'fg'], name='monday_revi_month_f2e31f_idx'),
        ),
        migrations.AddIndex(
            model_name='mondayreviewaction',
            index=models.Index(fields=['component_code'], name='monday_revi_compone_aa170f_idx'),
        ),
        migrations.AddIndex(
            model_name='fgplanfreeze',
            index=models.Index(fields=['month', 'fg'], name='fg_plan_fre_month_58863b_idx'),
        ),
        migrations.AddIndex(
            model_name='fgplanfreeze',
            index=models.Index(fields=['status'], name='fg_plan_fre_status_0dc853_idx'),
        ),
        migrations.AddIndex(
            model_name='fgplanfreeze',
            index=models.Index(fields=['month', 'week'], name='fg_plan_fre_month_0bbab2_idx'),
        ),
        migrations.AddConstraint(
            model_name='fgplanfreeze',
            constraint=models.UniqueConstraint(fields=('fg', 'month', 'week'), name='unique_fg_plan_freeze_per_week'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedulechangelog',
            index=models.Index(fields=['schedule'], name='delivery_sc_schedul_e9d627_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedulechangelog',
            index=models.Index(fields=['po_number'], name='delivery_sc_po_numb_c42b19_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedulechangelog',
            index=models.Index(fields=['component_code'], name='delivery_sc_compone_fca876_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryschedulechangelog',
            index=models.Index(fields=['-changed_at'], name='delivery_sc_changed_455d48_idx'),
        ),
    ]
