# Generated by Django 4.2.30 on 2026-10-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vendordeliveryschedule_mondayreviewaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='upload_batch',
            field=models.ForeignKey(blank=True, help_text='Upload batch audit reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_plans', to='core.uploadbatch'),
        ),
    ]
