# Generated by Django 4.2.30 on 2026-10-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_monthlyplan_upload_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryschedulechangelog',
            name='component_description',
            field=models.CharField(blank=True, default='', help_text='Denormalized component description for audit display', max_length=255),
        ),
        migrations.AddField(
            model_name='vendordeliveryschedule',
            name='upload_batch',
            field=models.ForeignKey(blank=True, help_text='Upload batch audit reference for bulk imports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_delivery_schedules', to='core.uploadbatch'),
        ),
    ]
