# Generated by Django 4.2.30 on 2026-10-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_upload_batch_and_component_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdefinition',
            name='month_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated month weight percentage: (week_working_days / total_working_days) * 100', max_digits=6),
        ),
    ]
